[package]
name = "m-ecu"
version = "0.5.8"
edition = "2021"

[dependencies]
cortex-m-rtic = { version = "1.1.4" }
stm32h7xx-hal = { version = "0.16", features = ["stm32h743v", "rt", "can"] }
vecraft = { version = "0.2.0", path = "../vecraft" }

[[bin]]
name = "m-ecu"
test = false
bench = false
